name: styleguard
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h5eee18b_1
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=py39h06a4308_0
  - attrs=24.3.0=py39h06a4308_0
  - babel=2.16.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py39h06a4308_0
  - bleach=6.2.0=py39h06a4308_0
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_1
  - comm=0.2.2=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.4=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.12.1=h4a9f257_0
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.15.0=py39h06a4308_0
  - ipywidgets=8.1.5=py39h06a4308_0
  - jedi=0.19.2=pyhff2d567_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py39h06a4308_0
  - jsonschema=4.23.0=py39h06a4308_0
  - jsonschema-specifications=2023.7.1=py39h06a4308_0
  - jupyter=1.1.1=py39h06a4308_0
  - jupyter-lsp=2.2.0=py39h06a4308_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=py39h06a4308_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=py39h06a4308_0
  - jupyter_server=2.14.1=py39h06a4308_0
  - jupyter_server_terminals=0.4.4=py39h06a4308_1
  - jupyterlab=4.3.4=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py39h06a4308_0
  - jupyterlab_widgets=3.0.13=py39h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=2.0.4=py39h06a4308_0
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.8.0=py39h06a4308_0
  - nbconvert=7.16.5=hd3eb1b0_0
  - nbconvert-core=7.16.5=py39h06a4308_0
  - nbconvert-pandoc=7.16.5=hd3eb1b0_0
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.3.2=py39h06a4308_0
  - notebook-shim=0.2.3=py39h06a4308_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.15=h5eee18b_0
  - overrides=7.4.0=py39h06a4308_0
  - packaging=24.2=pyhff2d567_1
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py39h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prometheus_client=0.21.0=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyqt=6.7.1=py39h6a678d5_0
  - pyqt6-sip=13.9.1=py39h5eee18b_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.20=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python-fastjsonschema=2.20.0=py39h06a4308_0
  - python-json-logger=3.2.1=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=25.1.2=py39h6a678d5_0
  - qtbase=6.7.2=hdaa5aa8_1
  - qtconsole=5.6.1=py39h06a4308_0
  - qtdeclarative=6.7.2=h6a678d5_0
  - qtpy=2.4.1=py39h06a4308_0
  - qtsvg=6.7.2=he621ea3_0
  - qttools=6.7.2=h80c7b02_0
  - qtwebchannel=6.7.2=h6a678d5_0
  - qtwebsockets=6.7.2=h6a678d5_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py39h06a4308_0
  - requests=2.32.3=py39h06a4308_1
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - rpds-py=0.22.3=py39h4aa5aa6_0
  - send2trash=1.8.2=py39h06a4308_1
  - setuptools=75.1.0=py39h06a4308_0
  - sip=6.10.0=py39h6a678d5_0
  - sniffio=1.3.0=py39h06a4308_0
  - soupsieve=2.5=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=py39h06a4308_0
  - tinycss2=1.4.0=py39h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.4.1=py39h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=1.8.0=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - widgetsnbextension=4.0.13=py39h06a4308_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - absl-py==2.1.0
    - accelerate==0.21.0
    - addict==2.4.0
    - aenum==3.1.16
    - aioboto3==13.2.0
    - aiobotocore==2.15.2
    - aiofiles==23.2.1
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aioitertools==0.12.0
    - aiosignal==1.3.2
    - albucore==0.0.24
    - albumentations==2.0.6
    - altair==5.5.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - basicsr==1.4.2
    - bitsandbytes==0.44.1
    - blendmodes==2022
    - boto3==1.35.36
    - botocore==1.35.36
    - cachetools==5.5.2
    - certifi==2024.8.30
    - chardet==5.2.0
    - charset-normalizer==3.4.0
    - clean-fid==0.1.35
    - click==8.1.7
    - clip==1.0
    - coloredlogs==15.0.1
    - colorlog==6.9.0
    - contourpy==1.3.0
    - cssselect2==0.8.0
    - cycler==0.12.1
    - cython==3.1.0
    - datasets==3.2.0
    - deeplake==3.9.34
    - deprecation==2.1.0
    - depth-anything==2024.1.22.0
    - diffusers==0.33.0.dev0
    - dill==0.3.9
    - easydict==1.13
    - einops==0.4.1
    - embreex==2.17.7.post6
    - eval-type-backport==0.2.2
    - facexlib==0.3.0
    - fastapi==0.94.0
    - ffmpy==0.5.0
    - filelock==3.16.1
    - filterpy==1.4.5
    - flatbuffers==25.2.10
    - fonttools==4.55.3
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - ftfy==6.3.1
    - future==1.0.0
    - fvcore==0.1.5.post20221221
    - gast==0.4.0
    - gfpgan==1.3.8
    - gitdb==4.0.12
    - gitpython==3.1.32
    - google-auth==2.38.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gradio==3.41.2
    - gradio-client==0.5.0
    - grpcio==1.71.0
    - h11==0.12.0
    - h5py==3.13.0
    - handrefinerportable==2024.1.18.0
    - hf-xet==1.1.1
    - httpcore==0.15.0
    - httpx==0.24.1
    - huggingface-hub==0.31.1
    - humanfriendly==10.0
    - humbug==0.3.2
    - idna==3.10
    - imageio==2.37.0
    - importlib-resources==6.4.5
    - inflection==0.5.1
    - insightface==0.7.3
    - iopath==0.1.9
    - jax==0.4.30
    - jaxlib==0.4.30
    - jinja2==3.1.4
    - jmespath==1.0.1
    - joblib==1.5.0
    - jsonmerge==1.8.0
    - keras==3.9.2
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.7
    - kornia==0.6.7
    - lark==1.1.2
    - lazy-loader==0.4
    - libclang==18.1.1
    - libdeeplake==0.0.152
    - lightning-utilities==0.12.0
    - llvmlite==0.43.0
    - lmdb==1.6.2
    - lpips==0.1.4
    - lxml==5.4.0
    - lz4==4.3.3
    - manifold3d==3.0.1
    - mapbox-earcut==1.0.3
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.4
    - mdurl==0.1.2
    - mediapipe==0.10.21
    - ml-dtypes==0.5.1
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.17
    - namex==0.0.8
    - narwhals==1.39.0
    - networkx==3.2.1
    - numba==0.60.0
    - numpy==2.0.2
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - oauthlib==3.2.2
    - omegaconf==2.2.3
    - onnx==1.18.0
    - onnxruntime==1.19.2
    - open-clip-torch==2.20.0
    - opencv-contrib-python==4.11.0.86
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.11.0.86
    - opt-einsum==3.3.0
    - optree==0.14.1
    - orjson==3.10.18
    - pandas==2.2.3
    - pathos==0.3.3
    - peft==0.7.0
    - piexif==1.1.3
    - pillow==9.5.0
    - portalocker==3.1.1
    - pox==0.3.5
    - ppft==1.7.6.9
    - prettytable==3.16.0
    - propcache==0.2.1
    - protobuf==5.29.4
    - psutil==5.9.5
    - pyarrow==18.1.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pycollada==0.9
    - pydantic==2.11.4
    - pydantic-core==2.33.2
    - pydub==0.25.1
    - pyjwt==2.10.1
    - pyparsing==3.2.0
    - python-dotenv==1.2.1
    - python-multipart==0.0.20
    - pytorch-fid==0.3.0
    - pytorch-image-generation-metrics==0.6.1
    - pytorch-lightning==1.9.4
    - pytz==2024.2
    - pywavelets==1.6.0
    - realesrgan==0.3.0
    - regex==2024.11.6
    - reportlab==4.4.0
    - requests-oauthlib==2.0.0
    - resize-right==0.0.2
    - rich==13.9.4
    - rsa==4.9
    - rtree==1.4.0
    - s3transfer==0.10.4
    - safetensors==0.5.3
    - scikit-image==0.21.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - shapely==2.0.7
    - simsimd==6.2.1
    - six==1.15.0
    - smmap==5.0.2
    - sounddevice==0.5.1
    - starlette==0.26.1
    - stringzilla==3.12.5
    - svg-path==6.3
    - svglib==1.5.1
    - sympy==1.13.1
    - tabulate==0.9.0
    - tb-nightly==2.20.0a20250512
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.19.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==1.1.0
    - threadpoolctl==3.6.0
    - tifffile==2024.8.30
    - timm==0.9.2
    - tokenizers==0.21.1
    - tomesd==0.1.3
    - torch==2.5.1
    - torchdiffeq==0.2.3
    - torchmetrics==1.6.1
    - torchsde==0.2.6
    - torchvision==0.20.1
    - tqdm==4.67.1
    - trampoline==0.1.2
    - transformers==4.51.3
    - trimesh==4.6.8
    - triton==3.1.0
    - typing-inspection==0.4.0
    - tzdata==2024.2
    - urllib3==1.26.20
    - uvicorn==0.34.2
    - vhacdx==0.0.8.post2
    - websockets==11.0.3
    - werkzeug==3.1.3
    - wrapt==1.12.1
    - xformers==0.0.28.post3
    - xxhash==3.5.0
    - yacs==0.1.8
    - yapf==0.43.0
    - yarl==1.18.3
prefix: /home/yjli/anaconda3/envs/styleguard
