{
  "compute_environment": "LOCAL_MACHINE",
  # "debug": false,
  "distributed_type": "MULTI_GPU",
  "downcast_bf16": false,
  # "enable_cpu_affinity": false,
  "machine_rank": 0,
  "main_training_function": "main",
  # "mixed_precision": "no",
  "num_machines": 1,
  "num_processes": 4,
  "rdzv_backend": "static",
  "same_network": false,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false,
  "main_process_port":8888,
  # "gpu_ids": '0,5,6,7',
  "mixed_precision": "bf16"
}
